/* tslint:disable */
/* eslint-disable */
/**
 * WeatherApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  WeatherDataDto,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    WeatherDataDtoFromJSON,
    WeatherDataDtoToJSON,
} from '../models/index';

export interface ApiWeatherGetRequest {
    latitude?: number;
    longitude?: number;
    date?: string;
}

/**
 * 
 */
export class WeatherApi extends runtime.BaseAPI {

    /**
     */
    async apiWeatherGetRaw(requestParameters: ApiWeatherGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeatherDataDto>> {
        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Weather`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeatherDataDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiWeatherGet(requestParameters: ApiWeatherGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeatherDataDto> {
        const response = await this.apiWeatherGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
