/* tslint:disable */
/* eslint-disable */
/**
 * WeatherApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FestivalDto
 */
export interface FestivalDto {
    /**
     * 
     * @type {number}
     * @memberof FestivalDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FestivalDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FestivalDto
     */
    date?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FestivalDto
     */
    location?: string | null;
}

/**
 * Check if a given object implements the FestivalDto interface.
 */
export function instanceOfFestivalDto(value: object): value is FestivalDto {
    return true;
}

export function FestivalDtoFromJSON(json: any): FestivalDto {
    return FestivalDtoFromJSONTyped(json, false);
}

export function FestivalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FestivalDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'date': json['date'] == null ? undefined : json['date'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function FestivalDtoToJSON(json: any): FestivalDto {
    return FestivalDtoToJSONTyped(json, false);
}

export function FestivalDtoToJSONTyped(value?: FestivalDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'date': value['date'],
        'location': value['location'],
    };
}

