/* tslint:disable */
/* eslint-disable */
/**
 * WeatherApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeatherDataDto
 */
export interface WeatherDataDto {
    /**
     * 
     * @type {number}
     * @memberof WeatherDataDto
     */
    temperature?: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherDataDto
     */
    condition?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WeatherDataDto
     */
    humidity?: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDataDto
     */
    windSpeed?: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDataDto
     */
    precipitation?: number;
}

/**
 * Check if a given object implements the WeatherDataDto interface.
 */
export function instanceOfWeatherDataDto(value: object): value is WeatherDataDto {
    return true;
}

export function WeatherDataDtoFromJSON(json: any): WeatherDataDto {
    return WeatherDataDtoFromJSONTyped(json, false);
}

export function WeatherDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'condition': json['condition'] == null ? undefined : json['condition'],
        'humidity': json['humidity'] == null ? undefined : json['humidity'],
        'windSpeed': json['windSpeed'] == null ? undefined : json['windSpeed'],
        'precipitation': json['precipitation'] == null ? undefined : json['precipitation'],
    };
}

export function WeatherDataDtoToJSON(json: any): WeatherDataDto {
    return WeatherDataDtoToJSONTyped(json, false);
}

export function WeatherDataDtoToJSONTyped(value?: WeatherDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'temperature': value['temperature'],
        'condition': value['condition'],
        'humidity': value['humidity'],
        'windSpeed': value['windSpeed'],
        'precipitation': value['precipitation'],
    };
}

